name: Build - macOS

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.os }} - SQLCipher ${{ matrix.sqlcipher }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-12]
        sqlcipher: ["0", "1"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          # Avoid Homebrew return non-zero exit code
          unset HOMEBREW_NO_INSTALL_FROM_API; brew untap homebrew/core; brew untap homebrew/cask; brew update
          brew tap sqlitebrowser/tap; brew install db4sqt@5 db4ssqlcipher db4ssqlitefts@5

      - name: Configure build
        run: |
          mkdir build && cd build
          cmake -DCMAKE_PREFIX_PATH=/usr/local/opt/qt@5 -Dsqlcipher=${{ matrix.sqlcipher }} ..

      - name: Build
        working-directory: ./build
        run: make -j3

      - name: Build extensions
        run: |
          clang -I /usr/local/opt/db4ssqlitefts@5/include -L /usr/local/opt/db4ssqlitefts@5/lib -fno-common -dynamiclib src/extensions/extension-formats.c
          clang -I /usr/local/opt/db4ssqlitefts@5/include -L /usr/local/opt/db4ssqlitefts@5/lib -fno-common -dynamiclib src/extensions/extension-functions.c
          curl -L -o src/extensions/fileio.c 'https://sqlite.org/src/raw?filename=ext/misc/fileio.c&ci=trunk'
          curl -L -o src/extensions/test_windirect.c 'https://sqlite.org/src/raw?filename=src/test_windirent.c&ci=trunk'
          curl -L -o src/extensions/test_windirect.h 'https://sqlite.org/src/raw?filename=src/test_windirent.h&ci=trunk'
          clang -I /usr/local/opt/db4ssqlitefts@5/include -L /usr/local/opt/db4ssqlitefts@5/lib -fno-common -dynamiclib src/extensions/fileio.c src/extensions/test_windirect.c