name: Build - macOS

on:
    schedule:
        - cron: '0 0 * * *' # Every day at midnight (UTC)
    workflow_call:
    workflow_dispatch:

permissions:
    contents: write

jobs:
    build:
        name: ${{ matrix.os }} - SQLCipher ${{ matrix.sqlcipher }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: true
            matrix:
                os: [macos-13-runner]
                sqlcipher: ["0", "1"]
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Configure build
              run: |
                if [ "${{ matrix.sqlcipher }}" = "1" ]; then
                    sed -i "" 's/"DB Browser for SQLite"/"DB Browser for SQLCipher-dev-'$(git rev-parse --short --verify HEAD)'"/' CMakeLists.txt
                else
                    sed -i "" 's/"DB Browser for SQLite"/"DB Browser for SQLite-dev-'$(git rev-parse --short --verify HEAD)'"/' CMakeLists.txt
                fi
                mkdir build && cd build
                cmake -G Ninja -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" -DcustomTap=1 -Dsqlcipher=${{ matrix.sqlcipher }} ..

            - name: Build
              working-directory: ./build
              run: ninja

            - name: Build Extension
              run: |
                clang -I /opt/homebrew/opt/db4subsqlitefts@5/include -L /opt/homebrew/opt/db4subsqlitefts@5/lib -fno-common -dynamiclib src/extensions/extension-formats.c
                clang -I /opt/homebrew/opt/db4subsqlitefts@5/include -L /opt/homebrew/opt/db4subsqlitefts@5/lib -fno-common -dynamiclib src/extensions/extension-functions.c
                curl -L -o src/extensions/fileio.c 'https://sqlite.org/src/raw?filename=ext/misc/fileio.c&ci=trunk'
                curl -L -o src/extensions/test_windirect.c 'https://sqlite.org/src/raw?filename=src/test_windirent.c&ci=trunk'
                curl -L -o src/extensions/test_windirect.h 'https://sqlite.org/src/raw?filename=src/test_windirent.h&ci=trunk'
                clang -I /opt/homebrew/opt/db4subsqlitefts@5/include -L /opt/homebrew/opt/db4subsqlitefts@5/lib -fno-common -dynamiclib src/extensions/fileio.c src/extensions/test_windirect.c

            - if: github.event_name != 'pull_request'
              name: Notarize the app
              uses: ./.github/actions/notarize-macos
              with:
                APPLE_ID: ${{ secrets.MACOS_CODESIGN_APPLE_ID }}
                APPLE_PW: ${{ secrets.MACOS_CODESIGN_APPLE_PW }}
                DEV_ID: ${{ secrets.MACOS_CODESIGN_DEV_ID }}
                KEYCHAIN_PATH: ${{ secrets.MACOS_CODESIGN_KEYCHAIN_PATH }}
                KEYCHAIN_PW: ${{ secrets.MACOS_CODESIGN_KEYCHAIN_PW }}
                SQLCIPHER: ${{ matrix.sqlcipher }}
                TEAM_ID: ${{ secrets.MACOS_CODESIGN_TEAM_ID }}

            - if: github.event_name != 'pull_request' && github.event_name != 'schedule'
              name: Release (Continuous)
              uses: softprops/action-gh-release@v1
              with:
                files: DB\ Browser\ for\ *.dmg
                prerelease: true
                tag_name: continuous

            # TODO: - if: github.event_name == 'schedule'