name: Build and Deploy Nightly Builds

on:
  schedule:
    - cron: '0 0 * * *' # Every day at midnight UTC
  workflow_dispatch:

jobs:
  build-appimage:
    if: needs.check-skip.outputs.skip != 'true'
    uses: ./.github/workflows/build-appimage.yml
    with:
      NIGHTLY: true
  build-macos:
    if: needs.check-skip.outputs.skip != 'true'
    uses: ./.github/workflows/build-macos.yml
    secrets: inherit
    with:
      NIGHTLY: true

  build-windows:
    if: needs.check-skip.outputs.skip != 'true'
    uses: ./.github/workflows/build-windows.yml
    secrets: inherit
    with:
      NIGHTLY: true

  release:
    needs: [build-macos, build-windows]
    uses: ./.github/workflows/release.yml
    secrets: inherit
    with:
      NIGHTLY: true
